import streamlit as st
import time

# -----------------------------
# Page Config
# -----------------------------
st.set_page_config(
    page_title="Resume Improver Demo",
    layout="wide"
)

# -----------------------------
# Session State Initialization
# -----------------------------
if "tab4_state" not in st.session_state:
    st.session_state.tab4_state = "idle"  # idle | generating | done

if "latex_code" not in st.session_state:
    st.session_state.latex_code = None

# -----------------------------
# Tabs
# -----------------------------
tabs = st.tabs([
    "Tab 1",
    "Tab 2",
    "Tab 3",
    "Improve Resume"
])

# -----------------------------
# Dummy Tabs
# -----------------------------
with tabs[0]:
    st.header("Tab 1")
    st.write("Other app content here")

with tabs[1]:
    st.header("Tab 2")
    st.write("Other app content here")

with tabs[2]:
    st.header("Tab 3")
    st.write("Other app content here")

# -----------------------------
# TAB 4 — FULL TAB TRANSITION
# -----------------------------
with tabs[3]:
    tab_container = st.container()

    # ---------- IDLE ----------
    if st.session_state.tab4_state == "idle":

        left, right = tab_container.columns([1, 2])

        with left:
            st.image(
                "Images/cv_template_hero.avif",
                caption="Create your own Professional Resume",
                use_container_width=True
            )

        with right:
            st.markdown("<div style='padding-top:120px; text-align:center'>", unsafe_allow_html=True)
            st.markdown(
                """
                <div style="text-align:center">
                    <div style="font-size:40px; font-weight:bold; color:#cdcdcd; margin-bottom:10px;">Ready to improve your resume?</div>
                    <div style="font-size:20px; color:#555;">Click the button below to generate a clean, ATS-friendly LaTeX resume.</div>
                </div>
                """,
                unsafe_allow_html=True
            )

            st.markdown("<div style='margin-top:40px'></div>", unsafe_allow_html=True)
            # Centered button in middle column
            col1, col2, col3 = st.columns([1, 2, 1])
            with col2:
                button_container = st.container()
                with button_container:
                    improve_clicked = st.button("🚀 Improve Resume", key="improve_resume",use_container_width=True)

            # Isolated CSS for ONLY this button
            st.markdown("""
            <style>
            div[data-testid="stContainer"] > div > button {
                width: 100% !important;
                padding: 25px 0 !important;
                font-size: 24px !important;
                border-radius: 12px !important;
                background-color: #4CAF50 !important;
                color: white !important;
            }
            div[data-testid="stContainer"] > div > button:hover {
                background-color: #45a049 !important;
            }
            </style>
            """, unsafe_allow_html=True)

            if improve_clicked:
                st.session_state.tab4_state = "generating"
                st.rerun()
    # ---------- GENERATING ----------
    elif st.session_state.tab4_state == "generating":

        # Spinner with isolated styling (no purple bar)
        tab_container.markdown("""
        <style>
        .spinner-title {
            font-size: 28px;
            font-weight: bold;
            color: #333 !important;
            background: none !important;
            padding: 0 !important;
            margin: 20px 0 10px 0 !important;
            box-shadow: none !important;
        }
        .spinner-text {
            font-size: 18px;
            color: #555 !important;
        }
        .loader {
            border: 10px solid #f3f3f3;
            border-top: 10px solid #4CAF50;
            border-radius: 50%;
            width: 80px;
            height: 80px;
            animation: spin 1s linear infinite;
            margin: auto;
        }
        @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
        </style>

        <div style="text-align:center; padding-top:120px">
            <div class="loader"></div>
            <div class="spinner-title">✨ Improving your resume</div>
            <div class="spinner-text">Please wait while we analyze and format your resume</div>
        </div>
        """, unsafe_allow_html=True)

        # ---------- SIMULATE LLM CALL ----------
        time.sleep(4)  # Replace this with your actual get_improved_resume() function

        st.session_state.latex_code = r"""
\documentclass{article}
\begin{document}
\section*{Improved Resume}
This is a sample LaTeX resume generated by the system.
\end{document}
"""
        st.session_state.tab4_state = "done"
        st.rerun()  # refresh to show generated resume

    # ---------- DONE STATE ----------
    elif st.session_state.tab4_state == "done":
        with tab_container:
            st.success("✅ Resume generated successfully")

            st.markdown("### Generated LaTeX Resume")
            st.code(st.session_state.latex_code, language="latex")

            # ---------- OPTION TO GENERATE AGAIN ----------
            if st.button("🔁 Generate Again"):
                st.session_state.tab4_state = "idle"
                st.session_state.latex_code = None
                st.rerun()
